# Generated by Django 5.2.8 on 2025-11-21 03:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('veterinario', 'Veterinario'), ('recepcionista', 'Recepcionista')], default='recepcionista', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('motivo', models.CharField(max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_curso', 'En Curso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('duracion_minutos', models.IntegerField(default=30)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True)),
                ('veterinario', models.ForeignKey(db_column='veterinario_id', on_delete=django.db.models.deletion.RESTRICT, related_name='citas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'db_table': 'citas',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('dni', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'ordering': ['apellido', 'nombre'],
                'indexes': [models.Index(fields=['dni'], name='clientes_dni_265cbd_idx'), models.Index(fields=['telefono'], name='clientes_telefon_4a8762_idx')],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('ave', 'Ave'), ('roedor', 'Roedor'), ('reptil', 'Reptil'), ('otro', 'Otro')], max_length=20)),
                ('raza', models.CharField(blank=True, max_length=100, null=True)),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=10)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('foto_url', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('fallecido', 'Fallecido'), ('transferido', 'Transferido')], default='activo', max_length=20)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.RESTRICT, related_name='mascotas', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'db_table': 'mascotas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_consulta', models.DateTimeField()),
                ('motivo_consulta', models.TextField()),
                ('sintomas', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField(blank=True, null=True)),
                ('tratamiento', models.TextField(blank=True, null=True)),
                ('peso_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('proxima_visita', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(db_column='cita_id', on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='core.cita')),
                ('veterinario', models.ForeignKey(db_column='veterinario_id', on_delete=django.db.models.deletion.RESTRICT, related_name='consultas', to=settings.AUTH_USER_MODEL)),
                ('mascota', models.ForeignKey(db_column='mascota_id', on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='core.mascota')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'db_table': 'consultas',
                'ordering': ['-fecha_consulta'],
            },
        ),
        migrations.AddField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(db_column='mascota_id', on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='core.mascota'),
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_vacuna', models.CharField(max_length=100)),
                ('fecha_aplicacion', models.DateField()),
                ('proxima_dosis', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(db_column='mascota_id', on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='core.mascota')),
                ('veterinario', models.ForeignKey(blank=True, db_column='veterinario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacunas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vacuna',
                'verbose_name_plural': 'Vacunas',
                'db_table': 'vacunas',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
        migrations.AddIndex(
            model_name='mascota',
            index=models.Index(fields=['cliente'], name='mascotas_cliente_9eb3f8_idx'),
        ),
        migrations.AddIndex(
            model_name='mascota',
            index=models.Index(fields=['especie'], name='mascotas_especie_d9d3f1_idx'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['mascota', '-fecha_consulta'], name='consultas_mascota_7f5e9a_idx'),
        ),
        migrations.AddIndex(
            model_name='consulta',
            index=models.Index(fields=['veterinario'], name='consultas_veterin_1e83e7_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha_hora'], name='citas_fecha_h_d81c1c_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['veterinario', 'fecha_hora'], name='citas_veterin_1cbd03_idx'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['estado'], name='citas_estado_03180e_idx'),
        ),
        migrations.AddIndex(
            model_name='vacuna',
            index=models.Index(fields=['mascota'], name='vacunas_mascota_92c9b7_idx'),
        ),
        migrations.AddIndex(
            model_name='vacuna',
            index=models.Index(fields=['proxima_dosis'], name='vacunas_proxima_ff7fc7_idx'),
        ),
    ]
